# Jekyll configuration
name: Schloss Fierralin
description: Software Developer
baseurl: /Literature

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

paginate: 3
paginate_path: "page_:num"
gems: [jekyll-paginate]